### ISSUE TITLE
Black screen on some images on rbk-dev

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/openseadragon-viewer#11]
I have tested random some images for the current `master` version on `rbk-dev` and some images are black.

See for example the differences on `rbk-dev` and `rbk-www` for these two cases:
 - `czi` file, `RID` = 16-2GM0
https://dev.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GM0
https://www.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GM0
 - `jpg` file, `RID` = 16-2GYG
https://dev.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GYG
https://www.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GYG

**Comment by carlkesselman** [comment]
Do we know why?

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Feb 29, 2020, 1:40 AM +0100, svoinea <notifications@github.com>, wrote:

I have tested random some images for the current master version on rbk-dev and some images are black.

See for example the differences on rbk-dev and rbk-www for these two cases:

  *   czi file, RID = 16-2GM0
https://dev.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GM0
https://www.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GM0
  *   jpg file, RID = 16-2GYG
https://dev.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GYG
https://www.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2GYG

**Comment by vipul-21** [comment]
Yes, I did find the reason for the jpg file. We were not handling the case
for simple files in the new code.
I am still working on the czi file issue.

**Comment by carlkesselman** [comment]
This is a czi file converted to pyramid tiff  and running out of the image server?

Carl



----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Feb 29, 2020, 3:13 PM -0800, Vipul Singh <notifications@github.com>, wrote:
Yes, I did find the reason for the jpg file. We were not handling the case
for simple files in the new code.
I am still working on the czi file issue.

**Comment by vipul-21** [comment]
I need to check that.

**Comment by carlkesselman** [comment]
Please do.  I don’t think we should spend any time debugging the old pipeline.

Carl

Sent from my iPhone

On Feb 29, 2020, at 3:23 PM, Vipul Singh <notifications@github.com> wrote:

﻿

I need to check that.

**Comment by hongsudt** [comment]
@svoinea Is this still an issue?
