### ISSUE TITLE
Channel control not getting rendered in Firefox

### ISSUE THREAD

**Issue by vipul-21** [informatics-isi-edu/openseadragon-viewer#13]
The channel control not showing up in the Firefox. The channel control is not able to render in the same manner as chrome with the slider to select the value for `brightness`, `contrast` or `hue`. 
Note: This issue was already there on `production` before merging the new code.

**Comment by hongsudt** [comment]
@rastogi-bhavya I think this is in one of the test cases.. So if the problem has been solved, please close the issue.

**Comment by rastogi-bhavya** [comment]
I tested for the following URL: https://dev.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2EC6?url=/iiif/2/https%3A%2F%2Fderiva-imaging.isi.edu%2Fimages%2F20160707-hKDCS19_133-JAM-0-30-000-3.tif/info.json&url=/~vipul/chaise-demo/data/20160707-hKDCS19-133-JAM-0-30-00_scene3_fixed.svg&channelName=TL%20Brightfield&meterScaleInPixels=455504&waterMark=GUDMAP.org 
Firefox version: 76.0.1 (64-bit)
As it can be seen in the screenshots that after changing the channel control is rendered, and changing the value causes the image to be changed as is expected.
![Screen Shot 2020-06-13 at 8 38 00 AM (2)](https://user-images.githubusercontent.com/17433752/84572873-d7a39680-ad51-11ea-9f6f-22f74e4ffaec.png)
![Screen Shot 2020-06-13 at 8 38 09 AM (2)](https://user-images.githubusercontent.com/17433752/84572876-d96d5a00-ad51-11ea-80ea-0a8a28412e6c.png)
