### ISSUE TITLE
User usability issues

### ISSUE THREAD

**Issue by vipul-21** [informatics-isi-edu/openseadragon-viewer#14]
- [x] Height of the channel control list is not dynamic 
- [ ] Viewer app should deal with login issue - the viewer app on full screen shows `No Slide Id` if the user is not logged in, instead of giving an appropriate error message.
- [x] Give spacing between each channel in the channel control so that the division between channels is more prominent.
- [ ] When the channel is opened for the no-channel case, it starts with a big area, then shrinks and when the button is closed, it again expands before closing.
- [ ] The left panel for annotations should move along with the title. Currently, the title is given a margin on page load and the left panel is shown after a while. [Issue Link](https://dev.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2EC6?url=/iiif/2/https%3A%2F%2Fderiva-imaging.isi.edu%2Fimages%2F20160707-hKDCS19_133-JAM-0-30-000-3.tif/info.json&url=/~vipul/chaise-demo/data/20160707-hKDCS19-133-JAM-0-30-00_scene3_fixed.svg&channelName=TL%20Brightfield&meterScaleInPixels=455504&waterMark=GUDMAP.org).

**Comment by RFSH** [comment]
With the recent changes to both OSD viewer and Chaise viewer, all the mentioned issues have been resolved.
