### ISSUE TITLE
Cleanup the repository

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#19]
Over the last year, the repository has gone through a process of upgrading and it was almost rewritten. While working on the upgrade, the old code wasn't touched to be able to test the old features and make sure the new implementation is not removing any features.

Now it's the time to do some cleanup and separate the old files. Going forward, only the upgraded version should be used by deployment. We can keep the old files for future references but shouldn't be easily accessible. In the following I will list the changes that I think we should make:

- [x] Remove `pview.html` as it's not used at all.
- [x] Cleanup README.md to remove any mention of `pview.html` and replace it with `mview.html`.
- [ ] Move `mview.html` and all of its `fonts`, `js`, and `css` dependencies to a folder called `old_viewer`. 
  - We don't want to completely remove the old files. This will allow us to test the old implementation. 
  - Make sure to only move the ones that are used by `mview.html`. Don't move the ones that are used by `index.html`.
  - Make sure the `old_viewer/mview.html` is functional. You might need to modify the `src` and `href` of these dependencies after moving. 
   - Don't move the `vendor` files that are used by `index.html`.
- [ ] Rename `index.html` to `mview.html`.
  - In some deployments and also during debugging we're still using `mview.html`. By making this change, we'll make sure that the new code is always used.
- [ ] Remove any unused file. This includes the `sample#.png` files.

_This is a work in progress. I will update the issue based on the new findings_

**Comment by vipul-21** [comment]
I've pushed the refactored code on the OSD branch name `refactored`. Since viewer app needed some changes with respect to these changes, there is a branch name `refactored` on chaise as well that aligns with the osd changes.

**Comment by hongsudt** [comment]
@RFSH close this issue after the code is merged.
