### ISSUE TITLE
Display: All/None functionality

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#23]
When the number of annotations to display for an image are more than zero and less than "All", both "All" and "None" checkboxes should be deselected.![Screen Shot 2020-06-03 at 3.04.37 PM.png](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/79c76c3f-021a-45f0-9c12-e31e9baf39ae)

**Comment by RFSH** [comment]
I feel like the current Display All/None and how it works is just confusing. It's not meant to show the current state of the page and is just meant to be used to force the state. Clicking on "Display all" should force all the annotations to show (and hide should hide all of them) regardless of how many annotations are displayed/hidden. Clicking on "All" should always do "display all" but it's currently toggling the button state (If the "All" is checked and you click on it, it will hide all the annotations.)

I suggest reworking it so we have two separate "Display all" and "Hide all" buttons. These buttons are supposed to be bulk controls and not a way to show the state of the page.
