### ISSUE TITLE
Empty search button positioning

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#24]
For the refactored branch of OSD, the button to empty the content of the search box is positioned at the bottom of the search box, whereas it should be on the right end of the box. ![Screen Shot 2020-06-03 at 3.10.40 PM.png](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/62b2e988-4ad8-4c22-ba16-10084151bb6a)![Screen Shot 2020-06-03 at 3.11.21 PM.png](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/4ebd7f81-0c7d-4cbe-8a90-d4d26154b6d9)

**Comment by RFSH** [comment]
This has been fixed in chaise.
