### ISSUE TITLE
Channel vs. Scene

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#25]
In the case of `czi` files (or based on code when the given `url` has `ImageProperties.xml`), we're properly merging different `url`s into one scene to show the different channels.  But in other cases, notably `iiif` (or based on code when the given `url` has `info.json`),  we're not properly showing a multi-channel scene. Even if the given `url`s are displaying the same image in different channels, we're displaying them in multiple scenes in osd-viewer.

We should fix this and be able to handle a multi-channel scene in all the different file types that we support.

**Comment by hongsudt** [comment]
This might be a duplicate of #20 or related to #20.

**Comment by carlkesselman** [comment]
I would argue that we should not be thinking about file types.  There is only one represention that we care about which is a set of channels and z planes for a image each with a different url

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Jun 4, 2020, 6:46 PM -0700, Hongsuda <notifications@github.com>, wrote:

This might be a duplicate of #20<https://github.com/informatics-isi-edu/openseadragon-viewer/issues/20> or related to #20<https://github.com/informatics-isi-edu/openseadragon-viewer/issues/20>.

**Comment by RFSH** [comment]
#51 has fixed this issue.
