### ISSUE TITLE
Empty elemets while adding new annotation

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#26]
While adding a new annotations, empty elements are created. This should not happen.

`<svg viewBox=‘0 0 17451 18493’ color=‘#DD57AA’  xmlns=‘http://www.w3.org/2000/svg’  xmlns:xlink=‘http://www.w3.org/1999/xlink’>
    <scale x=‘1’ y=‘1’/>
    <g id=‘2,Data Hub Attention’>
    <rect id=“2,Data Hub Attention” fill=“None” stroke=“#DD57AA” vector-effect=“non-scaling-stroke” x=“10975.354922063227” y=“10247.798577110423" height=“1067.318216636697” width=“3011.4418811524174" ></rect>
    <rect id=“2,Data Hub Attention” fill=“None” stroke=“#DD57AA” vector-effect=“non-scaling-stroke” ></rect>
    </g>
</svg>`

Here the second `rect` is created which is correct.

**Comment by rastogi-bhavya** [comment]
Current fix is a check while creating the output SVG. While creating the file, I am checking to see if each component has necessary features needed for it to be drawn. For eg, to draw a rectangle you need x, y, height, width. If any of this is not present it cannot be drawn.

The proper fix would be to not allow such a component to be created.

**Comment by rastogi-bhavya** [comment]
Empty SVG files should not be created. Example: if the user clicks on a drawing tool and clicks on the image and then clicks on save, an empty svg file (file having no elements like path, rect) is created and stored into the DB. When the page is reloaded this empty file is displayed in the annotations on the left hand side but there is no annotation drawn.

**Comment by RFSH** [comment]
@rastogi-bhavya This is done, right? if it is please close the issue.

**Comment by RFSH** [comment]
@rastogi-bhavya If this is not something that you're actively working on, change the pipeline to "this month". The bug is "fixed" and the rest of the changes that you described in your comment is just improvement for the code.

**Comment by RFSH** [comment]
The empty annotation is created when users start a drawing event, and we're making sure to remove it if it remains empty (user clicks on a drawing tool and never draws anything). So I'm going to close this issue.
