### ISSUE TITLE
channels should be displayed in order

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#27]
While displaying the channels, they should be displayed in a pre defined order.
![Screen Shot 2020-06-19 at 7.59.23 PM.png](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/1a69c020-9c1a-4ee6-b51f-e29bc40701e3)

https://dev.gudmap.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2GM0?waterMark=gudmap.org

**Comment by rastogi-bhavya** [comment]
The channels should be displayed in the order in which they are called from the URL parameters.

**Comment by rastogi-bhavya** [comment]
For the page https://dev.gudmap.org/~brastogi/chaise/viewer/#2/Gene_Expression:Image/RID=16-2GM0?waterMark=gudmap.org , the OSD URL (URL for full screen mode) is https://dev.gudmap.org/~brastogi/openseadragon-viewer/mview.html?waterMark=gudmap.org&url=/data/Immunofluorescence/2018/474b444175caa8f2f6ae7d81fc80f35d/AF647/ImageProperties.xml&url=/data/Immunofluorescence/2018/474b444175caa8f2f6ae7d81fc80f35d/AF480/ImageProperties.xml&url=/data/Immunofluorescence/2018/474b444175caa8f2f6ae7d81fc80f35d/DAPI/ImageProperties.xml&url=/data/Immunofluorescence/2018/474b444175caa8f2f6ae7d81fc80f35d/AF555/ImageProperties.xml .The code that generated the channels did not sort the channels in order.

**Comment by hongsudt** [comment]
You can now close the issue..

________________________________
