### ISSUE TITLE
output svg format

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#31]
The output created while writing (creating.editing) the svg annotation should have the following properties

1. id should be at the group level (root) and not in the children nodes
2. use svg standards like id, color instead of annotation-id, annotation-color
3. color should be defined at each node and not at the file level
4. Style attributes like fill should be inside style and not as a separate attribute in a node.

**Comment by RFSH** [comment]
#38 explains this in more detail.
