### ISSUE TITLE
Make the annotation lines easier to click

### ISSUE THREAD

**Issue by rastogi-bhavya** [informatics-isi-edu/openseadragon-viewer#34]
Add invisible border or increase the onclick area for these lines so that they are easier to click by the user

**Comment by RFSH** [comment]
@rastogi-bhavya Please add a comment and summarize the solution that you came up with and why we decided not to go with that solution. 

Please mention where in the code you were planning to change and also explain the issue that you faced while doing that (I remember you mentioned some issue that you didn't know how to solve)

**Comment by RFSH** [comment]
The solution that we found was adding a thicker invisible line below all the lines that are drawn in the SVG annotations. And then attach the click handlers to that thicker invisible line. To do this, after reading the annotations, we have to duplicate them and set the thickness for the invisible SVG elements to be bigger than the original. 

After discussing this further, this seemed like an unnecessary improvement given that the solution wasn't simple. This solution could also lead to more problems as it could make the annotations collide with each other and that could mess with the click handler events. So I'm going to close this issue.
