### ISSUE TITLE
Add color block to anatomy term corresponding to color used in annotation

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/openseadragon-viewer#41]
When a user creates an annotation, display a square/block of color on the anatomy term row in left panel that corresponds to the color used in the annotation. Requires communications between left panel and right panel.

**Comment by RFSH** [comment]
The following commits have been pushed to master for this change:

https://github.com/informatics-isi-edu/openseadragon-viewer/commit/3040ebd196fcd3df9c3f04bbbbf8a6cdb4c65cb9
https://github.com/informatics-isi-edu/chaise/commit/ebc58092096e5d1f3803280b092c710a4796bfdc

You should now see a colored block to the left of each annotation in the annotation list.

@crisaless Can you please verify and close this issue? You can use the following link to test this:
https://dev.gudmap.org/chaise/viewer/#2/Gene_Expression:Image/id=16-WWAP?waterMark=gudmap.org&meterScaleInPixels=4555361

**Comment by crisaless** [comment]
Looks great, thanks!
