### ISSUE TITLE
Add more drawing tools

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#52]
We should investigate other possible options (apart from path, rectangle, and circle that we have) for drawing annotations. This includes figuring out what's supported directly by d3 or finding widely used tools.

One obvious tool that we can add is multi-point lines.

**Comment by rastogi-bhavya** [comment]
Things to add
1. Straight line
2. Straight line with arrow
3. Polygon
4. Textbox

**Comment by rastogi-bhavya** [comment]
Tool-tips needs to added to the drawing tools.

Need to create documentation about how to properly use the annotation.

**Comment by RFSH** [comment]
The documentation has been added as part of [this PR in chaise](https://github.com/informatics-isi-edu/chaise/pull/2024)
