### ISSUE TITLE
Slider input for jump-to-z feature

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#82]
With the addition of the z-index input, users can jump to any specific z-index that they would like. But to do so, they would have to write the z-index. We could make this process easier by adding a slider that allows users to select z-index values from min to max. And after selecting the value, we would just call the same function as jump to z-index (if the specific z-index didn't exist its should already be handled.) So

- [ ] Modify the existing aggregate request to include min and max, and send min and max to osd viewer.
- [ ] Display a slider (most probably between the z-plane-list and z-plane-info).
- [ ] Make sure to call the proper function when the value changes.

A similar feature can be found here: http://homeros.kennedy.ox.ac.uk/webclient/img_detail/2209/?dataset=405

**Comment by rastogi-bhavya** [comment]
The min values means the value of the minimum available z index in the DB, similarly for max value.
After the user drags to a particular value, that z index or the closest z index to that value would be shown, along with appropriate message.

Q. Do we change the z plane list after this operation?

Q. How to position the UI?
